name: Wails build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            { name: shumai-dash, platform: linux/amd64, os: ubuntu-latest },
            { name: shumai-dash, platform: darwin/amd64, os: macos-latest },
            { name: shumai-dash, platform: darwin/arm64, os: macos-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          submodules: recursive
      - uses: cryptodeal/wails-bun-build-action@v0.0.3
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
